"""
mitre.py
--------
A tiny, offline lookup table mapping the MITRE ATT&CK technique IDs used
by the bundled rules (rules/*.yml) to their display name and tactic.

This intentionally only covers the techniques actually referenced by the
shipped rule pack -- it is not a full ATT&CK mirror. If you add rules
that reference new technique IDs, add an entry here too (or fall back to
the "Unknown technique" label handled gracefully by report.py).

Source: MITRE ATT&CK for Enterprise (https://attack.mitre.org), current
as of the ATT&CK release this project's rules were written against.
Always confirm technique details on attack.mitre.org for anything
customer-facing -- IDs are occasionally deprecated/merged between
ATT&CK versions.
"""
from __future__ import annotations

TECHNIQUES: dict[str, dict[str, str]] = {
    "T1098": {"name": "Account Manipulation", "tactic": "Persistence"},
    "T1136.001": {"name": "Create Account: Local Account", "tactic": "Persistence"},
    "T1070.001": {"name": "Indicator Removal: Clear Windows Event Logs", "tactic": "Defense Evasion"},
    "T1003.001": {"name": "OS Credential Dumping: LSASS Memory", "tactic": "Credential Access"},
    "T1059.001": {"name": "Command and Scripting Interpreter: PowerShell", "tactic": "Execution"},
    "T1548.002": {"name": "Abuse Elevation Control Mechanism: Bypass User Account Control", "tactic": "Privilege Escalation"},
    "T1569.002": {"name": "System Services: Service Execution", "tactic": "Lateral Movement / Execution"},
    "T1087": {"name": "Account Discovery", "tactic": "Discovery"},
    "T1082": {"name": "System Information Discovery", "tactic": "Discovery"},
    "T1016": {"name": "System Network Configuration Discovery", "tactic": "Discovery"},
    "T1078": {"name": "Valid Accounts", "tactic": "Defense Evasion / Persistence / Lateral Movement"},
    "T1021.001": {"name": "Remote Services: Remote Desktop Protocol", "tactic": "Lateral Movement"},
    "T1566.001": {"name": "Phishing: Spearphishing Attachment", "tactic": "Initial Access"},
    "T1204.002": {"name": "User Execution: Malicious File", "tactic": "Execution"},
}


def describe(technique_id: str) -> dict[str, str]:
    return TECHNIQUES.get(
        technique_id.upper(),
        {"name": "Unknown / not in local lookup", "tactic": "Unknown"},
    )


def attack_navigator_layer(technique_ids: list[str], layer_name: str = "win-ir-triage findings") -> dict:
    """Build a minimal MITRE ATT&CK Navigator layer (importable at
    https://mitre-attack.github.io/attack-navigator/) so findings can be
    viewed on the official ATT&CK matrix instead of just in our own report.
    """
    seen = sorted(set(t.upper() for t in technique_ids))
    return {
        "name": layer_name,
        "versions": {"attack": "15", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Auto-generated by win-ir-triage from detected events.",
        "techniques": [
            {
                "techniqueID": tid,
                "score": 1,
                "color": "#e60000",
                "comment": describe(tid)["name"],
                "enabled": True,
            }
            for tid in seen
        ],
        "gradient": {"colors": ["#ffffff", "#e60000"], "minValue": 0, "maxValue": 1},
        "legendItems": [{"label": "Detected in this triage run", "color": "#e60000"}],
    }
